### ISSUE TITLE
-profile option doesn't work

### ISSUE THREAD

**Issue by sepro** [screamer/netcoffee#1]
The -profile option is not recognized

**Comment by jhu99** [comment]
Please send me the test data, and your command line.
Jialu

**Comment by sepro** [comment]
On a fresh clone of the repository after compiling the software I used this command

``` bash
./bin/netcoffee -alignment -task 1 -out -alpha 0.3 -numspecies 4 -numthreads 1 -alignmentfile ./result/alignment_netcoffee.data -resultfolder ./result/ -profile test_profile.input
```

Return the following error.

```
Unknown option: -profile

Type './bin/netcoffee --help' to obtain a short summary on the usage.
```

I'm not well versed in C++ but I don't see any support for this option in the code (main.cpp). So probably the documentation needs an update to match the current version of the code.

**Comment by jhu99** [comment]
Sorry for the mistake. The profile option is ok now.
